### ISSUE TITLE
Make Browserify version

### ISSUE THREAD

**Issue by kahlil** [Cmdv/cycle-webpack-boilerplate#13]
@Cmdv do you have any requirements, preferences on how to tackle this? 
Otherwise I'd just go ahead and make a proposal after taking a closer look at your code.

**Comment by Cmdv** [comment]
@kahlil which ever way you see fit as I don't have extensive experience in Browserify.
The requirements from Webpack were: 
 
ES6 - with Babel.

SASS/CSS - What ever is the preferred way.

HOT-RELOADING - on both tests and app files. Currently all tests are compiled into a single file `./build/test.js`. Testem has a watch on that file. Webpack is split to pick up files in folders `__test__` and ending `nameOfFile.spec.js` for the `test.js` and the other Webpack config compiles the rest of the app.

I don't think there are any other requirements unless you can think of some :+1: 

Thanks for your input, after having a a Browserify version I'm going to try build a [Khaos](https://github.com/segmentio/khaos) template out of both version

**Comment by kahlil** [comment]
Sounds good. Will let you know when I have something. 

Just keeping @Widdershin's link here for reference and to find it later: https://github.com/widdershin/cycle-hot-reloading-example/

**Comment by Cmdv** [comment]
@kahlil :+1:

**Comment by kahlil** [comment]
@Cmdv I am sorry currently I have problems allocating the time for this. If anybody else would like to get going on this (@Widdershin?) I am more than happy to join in with concept and contribs by the end of next week of the week after.

**Comment by Cmdv** [comment]
Hi, @kahlil there is no rush. I've been trying to play about with Tylor's router and also not had time to do much in regards to this repo. I still need to do more tests and comments before it's ready really so no rush :smile:

**Comment by kahlil** [comment]
So I am finally working on the browserify version. My initial setup will slightly simpler than the Webpack version. Building of js and sass is working all with source maps (also for prod), it serves the app and it works \o/, hot reloading is something that I would add once everything else is working. 

The only thing I am having some problems with is to get how testem is intertwined with Webpack. My plan right now is to just integrate testem with default settings so it works as it is shown in the testem screencasts, that's also easier for people who are new to testem to learn about it works quickly. 

I had to think about this a little and I am afraid I am going (have) to take a rather selfish road here and set up the browserify boilerplate suited to my needs and taste. The reasons being I dont have the time to invest into making an exact copy of the Webpack version and I want to get to a setup that I can use to quickly build and prototype Cycle apps as soon as possible (my time resources are very limited and will remain that way for a long time). 

But here is what I am going to do: I am going to finish this as soon as possible so it suits my needs. Put it up on a repo and of course credit you for the original version and then if you or somebody else want to go ahead and modify it so it mirrors your boilerplate exactly you can use my boilerplate as a basis. 

Hope you are cool with this!

**Comment by Cmdv** [comment]
This sounds fine to me. One thing though is I've created a PR for the branch cyclic-router, which uses cyclic-router cyclic-history and a minimal state-driver. 

I've found this really useful set up when creating new apps so I'm not sure if you'd like to take a look at how it works and use that for your version of the boilerplate?

Either way use what you need out of this to build your own. Also I used webpack to compile all my tests in specific folders or maybe it was file names can't recall. Then testem has a watch on that single compiled file, so nothing too strainuous to replicate, unless there is a better method you use :)

**Comment by kahlil** [comment]
Oh nice! I will check that branch out. Are you going to move your code to the cyclic things for master too?

Thank you.

**Comment by kahlil** [comment]
When it comes to testem I am playing around with it. I really like the default behavior where it finds spec files by itself and just runs them. I want to see if I somehow can keep that behavior :)

**Comment by kahlil** [comment]
In the cyclic-router branch there is a weird bug with the tests. They don't run because `router.define(routes)` does not seem to work. It says `router` is undefined. Do you have the same problem? If just run tests that don't include the router it works. Any idea why that happens?

**Comment by Cmdv** [comment]
@kahlil yeah, not sure any of the tests will work actually I need to rewrite them as it's using an entirely different method!! I'll make that my next task. I was totally running the tests as I refactored honest!! :joy:  :joy:

**Comment by kahlil** [comment]
haha OK well that's fine them I guess I have enough to finish it up then. I'll just delete the tests that don't work and add them back in when you fixed them :laughing:

**Comment by Cmdv** [comment]
sounds like a very good plan :+1:

**Comment by Cmdv** [comment]
I'll close this as it has been created [HERE](https://github.com/kahlil/cycle-browserify-boilerplate)

😃
