### ISSUE TITLE
port 

### ISSUE THREAD

**Issue by brw31415** [Cmdv/cycle-webpack-boilerplate#18]
hi, i'm a newbie, whats the stndard way to change the port number?

**Comment by Cmdv** [comment]
Hi @brw31415 totally sorry for the delay missed this issue for some reason but if you require to change the port it's located in [this](https://github.com/Cmdv/cycle-webpack-boilerplate/blob/master/server.js#L24) part of the code :smile: 

```
.listen(3000, 'localhost', function (err) { // change the number 3000 to the port you require
```

**Comment by Cmdv** [comment]
I'll close this now as this
