### ISSUE TITLE
bundle.js loads as stylesheet

### ISSUE THREAD

**Issue by RainerAtSpirit** [Cmdv/cycle-webpack-boilerplate#3]
Very nice and small boilerplate. Exactly what I was looking for to get started with cyclyjs.

One small comment: There's probably no need to load bundle.js as stylesheet.
https://github.com/Cmdv/cycle-webpack-boilerplate/blob/master/index.html#L6

`<link rel="stylesheet" href="/build/bundle.js">`

**Comment by Cmdv** [comment]
Good catch I will remove it :+1:

**Comment by Cmdv** [comment]
I'll close now as it's fixed
